version: 2
updates:
- package-ecosystem: gomod
  directory: "/server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  rebase-strategy: disabled
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/react"
    versions:
    - 17.0.4
    - 17.0.8
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
    - 15.0.1
    - 15.0.3
    - 15.3.1
    - 15.6.0
  - dependency-name: sass
    versions:
    - 1.33.0
  - dependency-name: next
    versions:
    - 10.1.3
    - 10.2.2
  rebase-strategy: disabled
