version: '3.8'

services:
  client:
    build:
      context: ./
      dockerfile: docker/client/Dockerfile
    command: sleep infinity
    init: true
    volumes:
      - .:/workspace:cached

  server:
    build:
      context: ./
      dockerfile: docker/server/Dockerfile
    command: sleep infinity
    init: true
    ports:
      - "8080:8080"
    volumes:
      - .:/workspace:cached
