version: '3.8'

services:
  server:
    build:
      context: ./
      dockerfile: docker/server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      AZUKI_STORAGE_PATH: /volume
    volumes:
      - type: bind
        source: ./volume
        target: /volume

  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
      args:
        # app_conf: docker/nginx/dev.conf
        app_conf: docker/nginx/app.conf
    ports:
      - "8000:80"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
