version: '3.8'

services:
  client:
    build:
      context: ./
      dockerfile: docker/client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_ENDPOINT: http://localhost:8080

  server:
    build:
      context: ./
      dockerfile: docker/server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      AZUKI_STORAGE_PATH: /volume
    volumes:
      - type: bind
        source: ./volume
        target: /volume
