name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Run tests
        working-directory: server
        run: |
          go test -v
